trigger:
- main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'Jaya0116'
  location: 'central US'

stages:
- stage: DeployToAzure
  displayName: 'Deploy Azure Resources'
  jobs:
  - job: DeploymentJob
    displayName: 'Deploy Bicep Resources'
    steps:
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Install Microsoft Security DevOps Tool'

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: 'defenderdemo2'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --identity

    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: 'defenderdemo2'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location $(location)

    - task: AzureCLI@2
      displayName: 'Deploy Resources using Bicep'
      inputs:
        azureSubscription: 'defenderdemo2'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(resourceGroupName) --template-file main.bicep

    - task: AzureCLI@2
      displayName: 'Verify Deployment'
      inputs:
        azureSubscription: 'defenderdemo2'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az resource list --resource-group $(resourceGroupName)
